--- 
title: "Facters Affecting Movie Ratings"
author: "Jingyi Feng, Yuqing Hong, Siyu Shen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Nowadays, watching movies is common for most of us since it can help people relax and provide emotional value. The audience's evaluation of a movie is usually polarized. Professional film critics may evaluate a film from aspects such as picture composition and lens art. But for most of us, personal interest is the criterion for judging. We can notice that the rating of a movie is usually not proportional to the quality of the movie. 

Whether the genre of the movie or some other factor will determine a movie's rating in advance? Or whether some factors affect the tolerance of the audience, resulting in the difference in ratings? For example, we guess that documentary movies may be easier to obtain a high rating. On the one hand, audiences would easily resonate with this type of film which is more related to their real life. On the other hand, audiences will be more tolerant of filmmaking, for example, they won’t expect to see flashy special effects in a documentary movie. 

In this project, we are interested in the factors that may influence the ratings of a film (e.g. release time, genre, movie duration). We’ll try to answer this question by analyzing related datasets.
